### ISSUE TITLE
TLS

### ISSUE THREAD

**Issue by tomas-samot** [Nonobis/dockers#1]
How do I setup TLS using your docker image?

Line 42 should have this URL:
```
https://github.com/lucent-sea/Remotely/releases/latest/download/Remotely_Server_Linux-x64.zip
```
https://github.com/Nonobis/dockers/blob/master/remotely/Dockerfile#L42

**Comment by Nonobis** [comment]
Hello,

I have updated url, thanks 👍 

For tls, i don't know i use nginx as reverse proxy with NGinx Proxy Manager and Let's Encypt. I will investigate a little.

**Comment by tomas-samot** [comment]
Oh okay, I will look at the way you do it.

**Comment by chasekidder** [comment]
I've created a pull request to change the docker image over to using a self-signed certificate for TLS on the same port.

**Comment by Nonobis** [comment]
It's merged, sorry last month were hard ...
